### PR TITLE
add listbyDate, add listbyCategory add listbyTime, add listbyDateTime

### PR DESCRIPTION
**Pull request by yuchenlichuck**
add listbyDate, add listbyCategory add listbyTime, add listbyDateTime and some listcommand Junit test
Resolved some issues in #105

### CODE REVIEW

**Comment by JTWang2000** [comment]
Why do you add google code style? @yuchenlichuck

**Comment by yuchenlichuck** [comment]
@JTWang2000 I thought I can reformat the code automatically. But it is a kind of different from the checkstyle.xml. Let me delete it in the next push

**Comment by yuchenlichuck** [comment]
#106

**Comment by yuchenlichuck** [comment]
If there is nothing wrong, I would merge it Wednesday night~ @JTWang2000

**Pull request merged**
