### PR TITLE
Added JUnit tests

### PR DESCRIPTION
**Pull request by Bencotti**
100% coverage / lines for Calendar and Done command

Added for ExitCommand

### CODE REVIEW

**Comment by rsanchez-macias** [comment]
The changes look good 👍 I cannot merge because there is a merge conflict

**Comment by Bencotti** [comment]
Yeah it’s because I merged the few PRs below this. I’ll fix it again after I wake

**Comment by rsanchez-macias** [comment]
Okidoki sounds good :)

**Comment by JTWang2000** [comment]
> Yeah it’s because I merged the few PRs below this. I’ll fix it again after I wake

I have solved the conflicts and I will merge if all checks passed.

**Pull request merged**
