### PR TITLE
DG: Add Storage component

### PR DESCRIPTION
**Pull request by rsanchez-macias**
Added some diagrams related to storage to the DG

### CODE REVIEW

**Comment by rsanchez-macias** [comment]
The patch to the "The input string: ' ' " is also here

**Comment by rsanchez-macias** [comment]
Just spotted an error I will fix it rn

**Comment by JTWang2000** [comment]
> The patch to the "The input string: ' ' " is also here

Just want to merge haha

**Comment by rsanchez-macias** [comment]
I should've done two separate PR's 😅

**Pull request merged**
